export const MATCH = {
	events: [
		{
        "Date": "2020-08-01T18:45:00+00:00",
        "League": "Serie A",
        "Round": "38",
        "HomeTeam": "Milan",
		"HomeTeam_Id": "133667",
		"HomeTeamLogo": "https://logos-world.net/wp-content/uploads/2020/11/Milan-Logo.png",
        "AwayTeam": "Cagliari",
        "AwayTeam_Id": "134783",
		"AwayTeamLogo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFs7e3y737vQ_YI4YD2Qqctn_TOD9YnQNm98riTixEksJvBjEtQq5dV1Efw5QfCsRD9YE&usqp=CAU",
        "Time": "73'",
        "HomeGoals": "3",
        "AwayGoals": "0",
        "HomeGoalDetails": "11':Ragnar Klavan (Own goal);44':Zlatan Ibrahimovic;55':Zlatan Ibrahimovic;57':Samuel Castillejo;",
        "AwayGoalDetails": {},
        "HomeLineupGoalkeeper": "Gianluigi Donnarumma; ",
        "AwayLineupGoalkeeper": "Alessio Cragno; ",
        "HomeLineupDefense": "Davide Calabria; Simon Kjaer; Matteo Gabbia; Theo Hernandez; ",
        "AwayLineupDefense": "Sebastian Walukiewicz; Luca Ceppitelli; Fabio Pisacane; ",
        "HomeLineupMidfield": "Ismael Bennacer; Franck Kessie; Alexis Saelemaekers; Hakan Calhanoglu; Rafael Leao; ",
        "AwayLineupMidfield": "Paolo Farago; Nahitan Nandez; Riccardo Ladinetti; Artur Ionita; Federico Mattiello; ",
        "HomeLineupForward": "Zlatan Ibrahimovic; ",
        "AwayLineupForward": "Alberto Paloschi; Giovanni Simeone; ",
        "HomeLineupSubstitutes": "Asmir Begovic; Antonio Donnarumma; Giacomo Bonaventura; Lucas Biglia; Lorenzo Colombo; Lucas Paqueta; Leo Duarte; Alexis Saelemaekers; Diego Laxalt; Marco Brescianini; Daniel Maldini; Emanuele Torrasi; ",
        "AwayLineupSubstitutes": "Rafael; Giuseppe Ciocci; Alberto Paloschi; Valter Birsa; Fabio Pisacane; Federico Marigosu; Alessandro Lombardi; Leonardo Pavoletti; Riccardo Ladinetti; Andrea Carboni; Luca Gagliano; Isaias Delpupo; ",
        "HomeSubDetails": "38': out Rafael Leao;38': in Giacomo Bonaventura;65': out Samuel Castillejo;65': in Daniel Maldini;66': out Ismael Bennacer;66': in Marco Brescianini;66': out Hakan Calhanoglu;66': in Alexis Saelemaekers;",
        "AwaySubDetails": "62': out Ragnar Klavan;62': in Riccardo Ladinetti;62': out Luca Ceppitelli;62': in Andrea Carboni;62': out Gaston Pereiro;62': in Alberto Paloschi;",
        "Location": "San Siro",
        "Stadium": "San Siro",
        "HomeTeamYellowCardDetails": "67':Alexis Saelemaekers;",
        "AwayTeamYellowCardDetails": "13':Luca Ceppitelli;13':Gaston Pereiro;45':Paolo Farago;59':Alessio Cragno;",
        "HomeTeamRedCardDetails": {},
        "AwayTeamRedCardDetails": {},
        "HasBeenRescheduled": "true"
      },
      {
        "Date": "2020-08-01T18:45:00+00:00",
        "League": "Serie A",
        "Round": "38",
        "HomeTeam": "Napoli",
		"HomeTeam_Id": "133670",
		"HomeTeamLogo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjy6pK3ynlDIQgaIhPp5dP0z3nmdYft13DGA&usqp=CAU",
        "AwayTeam": "Lazio",
        "AwayTeam_Id": "133668",
		"AwayTeamLogo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6Sja8-lpATgcXaNN10mV9fJ-6uqbzwNMDsAE9aG0tVkkkefgXk_qfpxjoTWhc6OvIfL0&usqp=CAU",
        "Time": "67'",
        "HomeGoals": "2",
        "AwayGoals": "1",
        "HomeGoalDetails": "9':Fabian;54':Lorenzo Insigne;",
        "AwayGoalDetails": "22':Ciro Immobile;",
        "HomeLineupGoalkeeper": "David Ospina; ",
        "AwayLineupGoalkeeper": "Thomas Strakosha; ",
        "HomeLineupDefense": "Giovanni Di Lorenzo; Kalidou Koulibaly; Sebastiano Luperto; Elseid Hysaj; ",
        "AwayLineupDefense": "Patric; Luiz Felipe; Francesco Acerbi; ",
        "HomeLineupMidfield": "Fabian; Stanislav Lobotka; Piotr Zielinski; ",
        "AwayLineupMidfield": "Manuel Lazzari; Sergej Milinkovic-Savic; Marco Parolo; Luis Alberto; Adam Marusic; ",
        "HomeLineupForward": "Jose Maria Callejon; Dries Mertens; Lorenzo Insigne; ",
        "AwayLineupForward": "Ciro Immobile; Joaquin Correa; ",
        "HomeLineupSubstitutes": "Orestis Karnezis; Diego Demme; Allan; Hirving Lozano; Eljif Elmas; Sebastiano Luperto; Nikola Maksimovic; Matteo Politano; Elseid Hysaj; Faouzi Ghoulam; Amin Younes; Arkadiusz Milik; ",
        "AwayLineupSubstitutes": "Guido Guerrieri; Silvio Proto; Jordan Lukaku; Djavan Anderson; Nicolo Armini; Bastos; Felipe Caicedo; Jony; Andre Anderson; Danilo Cataldi; Bobby Adekanye; Denis Vavro; ",
        "HomeSubDetails": {},
        "AwaySubDetails": "63': out Patric;63': in Denis Vavro;63': out Francesco Acerbi;63': in Bastos;",
        "Location": "Stadio San Paolo",
        "Stadium": "Stadio San Paolo",
        "HomeTeamYellowCardDetails": "15':Kalidou Koulibaly;",
        "AwayTeamYellowCardDetails": {},
        "HomeTeamRedCardDetails": {},
        "AwayTeamRedCardDetails": {},
        "HasBeenRescheduled": "true"
      },
      {
        "Date": "2020-08-01T18:45:00+00:00",
        "League": "Serie A",
        "Round": "38",
        "HomeTeam": "Atalanta",
        "HomeTeam_Id": "134782",
		"HomeTeamLogo": "https://upload.wikimedia.org/wikipedia/en/thumb/6/66/AtalantaBC.svg/130px-AtalantaBC.svg.png",
        "AwayTeam": "Inter",
        "AwayTeam_Id": "133681",
		"AwayTeamLogo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA-WNu4o252boTe29w3eN42mBvLlBrX27ORw&usqp=CAU",
        "Time": "67'",
        "HomeGoals": "0",
        "AwayGoals": "2",
        "HomeGoalDetails": {},
        "AwayGoalDetails": "2':Danilo D'Ambrosio;20':Ashley Young;",
        "HomeLineupGoalkeeper": "Pierluigi Gollini; ",
        "AwayLineupGoalkeeper": "Samir Handanovic; ",
        "HomeLineupDefense": "Rafael Toloi; Mattia Caldara; Berat Djimsiti; ",
        "AwayLineupDefense": "Milan Skriniar; Stefan de Vrij; Diego Godin; ",
        "HomeLineupMidfield": "Hans Hateboer; Marten de Roon; Remo Freuler; Timothy Castagne; Alejandro Gomez; Mario Pasalic; ",
        "AwayLineupMidfield": "Danilo D'Ambrosio; Nicolo Barella; Marcelo Brozovic; Roberto Gagliardini; Ashley Young; ",
        "HomeLineupForward": "Duvan Zapata; ",
        "AwayLineupForward": "Romelu Lukaku; Lautaro Martinez; ",
        "HomeLineupSubstitutes": "Francesco Rossi; Marco Sportiello; Bosko Sutalo; Adrien Tameze; Lennart Czyborra; Luis Muriel; Rodrigo Guth; Ruslan Malinovsky; Jacopo Da Riva; Raoul Bellanova; Hans Hateboer; Ebrima Colley; ",
        "AwayLineupSubstitutes": "Daniele Padelli; Tommaso Berni; Alexis Sanchez; Victor Moses; Andrea Ranocchia; Borja Valero; Christian Eriksen; Sebastiano Esposito; Lucien Agoume; Cristiano Biraghi; Milan Skriniar; Antonio Candreva; ",
        "HomeSubDetails": "5': out Pierluigi Gollini;5': in Marco Sportiello;61': out Timothy Castagne;61': in Hans Hateboer;62': out Mario Pasalic;62': in Luis Muriel;62': out Remo Freuler;62': in Ruslan Malinovsky;",
        "AwaySubDetails": {},
        "Location": "Stadio Atleti Azzurri d'Italia",
        "Stadium": "Stadio Atleti Azzurri d'Italia",
        "HomeTeamYellowCardDetails": "26':Berat Djimsiti;44':Rafael Toloi;",
        "AwayTeamYellowCardDetails": "23':Stefan de Vrij;56':Marcelo Brozovic;",
        "HomeTeamRedCardDetails": {},
        "AwayTeamRedCardDetails": {},
        "HasBeenRescheduled": "true"
      },
      {
        "Date": "2020-08-01T18:45:00+00:00",
        "League": "Serie A",
        "Round": "38",
        "HomeTeam": "Juventus",
        "HomeTeam_Id": "133676",
		"HomeTeamLogo": "https://i.pinimg.com/originals/f5/69/ff/f569fff142158f69809575318a8f7995.png",
        "AwayTeam": "Roma",
        "AwayTeam_Id": "133682",
		"AwayTeamLogo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI5E7GKbhxv3zKZAZLphQm6LZ5QI_nFvozIQ&usqp=CAU",
        "Time": "72'",
        "HomeGoals": "1",
        "AwayGoals": "3",
        "HomeGoalDetails": "6':Gonzalo Higuain;",
        "AwayGoalDetails": "23':Nikola Kalinic;44':Diego Perotti;52':Diego Perotti;",
        "HomeLineupGoalkeeper": "Wojciech Szczesny; ",
        "AwayLineupGoalkeeper": "Daniel Fuzato; ",
        "HomeLineupDefense": "Danilo; Daniele Rugani; Leonardo Bonucci; Gianluca Frabotta; ",
        "AwayLineupDefense": "Yildirim Cetin; Roger Ibanez; Federico Fazio; ",
        "HomeLineupMidfield": "Adrien Rabiot; Rodrigo Bentancur; Simone Muratore; ",
        "AwayLineupMidfield": "Davide Zappacosta; Gonzalo Villar; Bryan Cristante; Riccardo Calafiori; Nicolo Zaniolo; Diego Perotti; ",
        "HomeLineupForward": "Luca Zanimacchia; Gonzalo Higuain; Federico Bernardeschi; ",
        "AwayLineupForward": "Nikola Kalinic; ",
        "HomeLineupSubstitutes": "Carlo Pinsoglio; Gianluigi Buffon; Giorgio Chiellini; Aaron Ramsey; Alex Sandro; Juan Cuadrado; Merih Demiral; Rodrigo Bentancur; Marco Olivieri; Wesley; Giacomo Vrioni; Daouda Peeters; ",
        "AwayLineupSubstitutes": "Pau Lopez; Juan Jesus; Edin Dzeko; Aleksandar Kolarov; Yildirim Cetin; Cengiz Under; Davide Santon; Carles Perez; Amadou Diawara; Henrikh Mkhitaryan; Justin Kluivert; Bruno Peres; ",
        "HomeSubDetails": "51': out Adrien Rabiot;51': in Aaron Ramsey;51': out Leonardo Bonucci;51': in Merih Demiral;",
        "AwaySubDetails": "56': out Roger Ibanez;56': in Juan Jesus;56': out Nicolo Zaniolo;56': in Cengiz Under;56': out Bryan Cristante;56': in Davide Santon;61': out Riccardo Calafiori;61': in Bruno Peres;",
        "Location": "Juventus Stadium",
        "Stadium": "Juventus Stadium",
        "HomeTeamYellowCardDetails": "21':Daniele Rugani;",
        "AwayTeamYellowCardDetails": "40':Chris Smalling;45':Diego Perotti;54':Bryan Cristante;",
        "HomeTeamRedCardDetails": {},
        "AwayTeamRedCardDetails": {},
        "HasBeenRescheduled": "true"
      }
	]
};